### PR TITLE
Fix type conversions between vector types

### PR DESCRIPTION
**Pull request by mscastanho**
Build with GCC 11.1 was broken because of some implicit type conversions,
causing the compilation to fail with many errors like this:

```
$ pveclib/src/pveclib/vec_int128_ppc.h:4610:22: error: incompatible types when
assigning to type ‘vui128_t’ {aka ‘__vector(1) __int128 unsigned’} from type
‘vb128_t’ {aka ‘__vector(1) __int128’}
 4610 |               vsgn = vec_setb_sq (vra);
      |                      ^~~~~~~~~~~
```

Some of these were caused by testsuite wrappers with different signatures from
their inner functions and also some missing casts on the definitions of
vec_sraq, vec_sraqi, and vec_setb_ncq.

### CODE REVIEW

**Comment by mscastanho** [comment]
This should fix the issue seen on advancetoolchain/advance-toolchain#2211

**Review by munroesj52 — APPROVED** [review]
Looks good to me

**Comment by munroesj52** [comment]
Please add you approval to https://github.com/open-power-sdk/pveclib/pull/147 and I can merge the set?

**Comment by munroesj52** [comment]
Merging complete set for P10/ GCC 11.2 changes.
